# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: ./gradlew build
      
  sonarcloud:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: SonarQube and Jacoco
      run: ./gradlew test jacocoTestReport sonarqube -Dsonar.login=$SONAR_TOKEN      
      env: 
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: Jacoco Test-Report
        path: build/reports/jacoco/test/html
    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: Gradle Test report
        path: build/reports/tests/test
